### ISSUE TITLE
failed job at "collect at SparkSqlDFOptimizerRule.scala"

### ISSUE THREAD

**Issue by rogerrogeryau** [SaurabhChawla100/spark-radiant#3] opened 2022-08-17 13:53 UTC
hi ,

I spark-submit with the below arguments on my emr cluster (EMR release 6.6.0). 

` --packages "io.github.saurabhchawla100:spark-radiant-sql:1.0.4,io.github.saurabhchawla100:spark-radiant-core:1.0.4" \
 --conf spark.extraListeners=com.spark.radiant.core.SparkJobMetricsCollector \`

with .py script with the below code snippet

`from sparkradiantsqlpy import SparkRadiantSqlApi
`
`
SparkRadiantSqlApi(spark).addExtraOptimizerRule()
`

But the jobs failed at `collect at SparkSqlDFOptimizerRule.scala`

<img width="1780" alt="image" src="https://user-images.githubusercontent.com/25982232/185149211-c2ebdb0c-6001-4962-bb6d-d22068e4692d.png">

The spark job itself runs without error except the above mentioned SparkSqlDFOptimizerRule job, and yet it takes 4x more time, when compared with the original one, to complete. 

Provided that, I run the two tests separately and no other job running on background on the same cluster.

May I have your advice in using it? I am not sure what went wrong. Many thanks!!

**Comment by SaurabhChawla100** [comment] 2022-08-17 16:29
@rogerrogeryau - Thank you for using the spark-radiant.

There is no need to use the 

```
from sparkradiantsqlpy import SparkRadiantSqlApi
SparkRadiantSqlApi(spark).addExtraOptimizerRule()
```

from spark-radiant-1.0.3 you just have to give this conf 
`--conf spark.sql.extensions=com.spark.radiant.sql.api.SparkRadiantSqlExtension`
This will add all OptimizerRule from spark Radiant. This will work for all the spark submit  scala, python, spark-sql, Java etc

```
--packages "io.github.saurabhchawla100:spark-radiant-sql:1.0.4,io.github.saurabhchawla100:spark-radiant-core:1.0.4" \ --conf spark.extraListeners=com.spark.radiant.core.SparkJobMetricsCollector \ --conf spark.sql.extensions=com.spark.radiant.sql.api.SparkRadiantSqlExtension
```

##Secondly related to failing of `collect at SparkSqlDFOptimizerRule.scala` 
Can you share below information - 
1) What kind join it is (inner join, outer join etc)?
2) Is number of records from which is dynamic filter is computed is huge?
3) Please share any sample code what exactly you are trying accomplished in pyspark
4) what version of spark you are using

Some information related to Dynamic filter
1) This works for equi-join conditions.
2) This dynamic filter works well when we get the filter records from the smaller table within the threshold limit for completion. This controlled by this conf

```
spark.sql.dynamicFilter.completion.threshold - This is the time to complete the dynamic filter optimisation in spark. This is to prevent the scenario where the smaller table where predicates filtering is huge and not completed in threshold time. Its value is in seconds. The default value is 60.
```

So by default threshold value is 60 sec, if the dynamic filter is not computed within 60 secs. Then we stopped running the Dynamic filtering and we kill all the jobs which are responsible for creating the Dynamic filter. That's my suspect at this point of time that dynamic filter is not completed in 60 sec. Since it is not getting benefit from  Dynamic filter, so spark job run with optimizer rule that comes with apache spark. 

You can try increasing the value of conf  `--conf spark.sql.dynamicFilter.completion.threshold=120` or 180 or 240. To see if you are getting any benefit from  Dynamic filter.

For more information - please refer the doc [https://github.com/SaurabhChawla100/spark-radiant/blob/master/docs/dynamicFilterInSpark.md]

This what I suspect, based on my initial analysis. I hope this will help you in getting the understanding about the issue.

**Comment by rogerrogeryau** [comment] 2022-08-18 14:21
thanks for reply, @SaurabhChawla100 . Kindly please find the below information useful. 

Q. What kind join it is (inner join, outer join etc)?
A. From the testing runs, it consists of both inner and outer joins from different tables in the datalake. And it mimics the parts of the ETL spark sql jobs.
Q. Is number of records from which is dynamic filter is computed is huge?
A. Just for testing purpose, the queries doesn't process huge dataset. ( less than a million records for each table)
Q. Please share any sample code what exactly you are trying accomplished in pyspark
A. Probably i need more time on create dummy datasets to reproduce the result. Any chance that you could advise me on what situation should I use / not use the provided config/ feature? I was trying to use / enable that feature config on a long running cluster that consists various kinds of spark queries. Kindly please advise whether it's expected. Or should I use it only for specific types of query / joins ? 
Q. what version of spark you are using
A. Spark 3.2.0

Many thanks once again. One more thing to note is that, any similar use case / feature like dr.elephant / sparklens on the future? It will be great.

**Comment by SaurabhChawla100** [comment] 2022-08-22 09:02
@rogerrogeryau - Dynamic Filter join works well for the below scenario 
```
Spark-Radiant Dynamic Filter works well for the Join which is a type of star schema, where one table consists of large 
number of records as compared to other tables. This Dynamic Filtering works on runtime by using the predicates from the
 smaller table and filter out the join columns from the smaller table used those predicates result on the bigger table and filter
 out the bigger table, resulting in the less expensive join. Since the number of records on the left side is reduced resulting in improving the performance of the Spark Sql Queries.
```

That is the reason if the computation of dynamic filter is not completed in the threshold `spark.sql.dynamicFilter.completion.threshold` time we kill the jobs that are computing the dynamic filter. So there is need to tune(120 or 180) this threshold to see if your existing load is getting benefit.

` Probably i need more time on create dummy datasets to reproduce the result.` - It will be helpful if you create some dummy set and reproduce the result.

`Many thanks once again. One more thing to note is that, any similar use case / feature like dr.elephant / sparklens on the future? It will be great.` - There is already a module for observability of Spark Application in spark-radiant-core, will be adding more features to it in future

```
 Metrics Collector - SparkJobMetricsCollector is used for collecting the important metrics to Spark Driver Memory, Stage metrics, Task Metrics. This is enabled by using the configuration --conf spark.extraListeners=com.spark.radiant.core.SparkJobMetricsCollector and providing the jars in the class path. User can
 also Publish the metrics by their own custom Publisher class by extending the org.apache.spark.PublishMetrics interface 
and override the publishStageLevelMetrics method. SamplePublishMetrics class already added in project for reference and 
there is need to provide the custom Publish class name in this conf while running the spark Application --conf 
spark.radiant.metrics.publishClassName=com.spark.radiant.core.SamplePublishMetrics

  ./bin/spark-shell --conf spark.extraListeners=com.spark.radiant.core.SparkJobMetricsCollector --packages "io.github.saurabhchawla100:spark-radiant-sql:1.0.4,io.github.saurabhchawla100:spark-radiant-core:1.0.4" 

```

Please refer readme doc for the same https://github.com/SaurabhChawla100/spark-radiant

sharing some more links for reference - [links](https://dzone.com/articles/spark-radiant-apache-spark-performance-and-cost-op)

[link2](https://medium.com/p/20925df69529)

**Comment by SaurabhChawla100** [comment] 2022-09-19 04:47
Closing this issue, Already shared steps for running Dynamic Filters , and also shared the info related to SparkJobMetricsCollector

**Closed as completed by SaurabhChawla100** 2022-09-19 04:47 UTC
